name: DEV - Tutorial Backend Deploy

on:
  repository_dispatch:
    types: [ps-tutorial-backend-cd-dev]
  workflow_dispatch:

env:
  REPOSITORY: "puwanai-s/ps-tutorial-backend"
  APP_NAME: ps-tutorial-backend
  AZURE_WEB_APP_NAME: app-ps-tutorial-backend-dev-001
  CONTAINER_REPOSITORY: "acrpstutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  build-and-deploy-app-service:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: "Checkout pipelines"
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        allow-no-subscriptions: true
    
    - name: 'Set subscription'
      run: az account set --subscription 650b5d3c-6aed-4f80-b2d4-6c7996b9e376
    
    - name: "Deploy to Azure WebApp"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        images: '${{ env.CONTAINER_REPOSITORY }}/${{ env.APP_NAME }}:${{env.IMAGE_TAG}}'
    
    - name: Set Web App Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        app-settings-json: |
          [
            {
              "name": "MONGODB_CONNECTION_STRING",
              "value": "mongodb://cosmos-ps-tutorial-dev-001:jWC4kU2fO6gryXdrHFY2Q5qpmVevMFMx86mD3OLZxDaBDVHo2a3yWcNmjQwRswgtbeqJr0IAAV2dyKgKeej9mQ==@cosmos-ps-tutorial-dev-001.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmos-ps-tutorial-dev-001@",
              "slotSetting": false
            },
            {
              "name": "PORT",
              "value": "80",
              "slotSetting": false
            }
          ]